title: Niklas von Moers
logo: "/profile_picture.jpg?raw=true"
description: >
  I am a Data Science consultant at crossnative GmbH with a background in mathematics, located in Hamburg, Germany. I am interested in MLOps, software engineering, data visualizations and many other things data.
  <br><br>
  <a href="https://www.linkedin.com/in/niklas-von-moers-a150071b4/" target="_blank" rel="noopener noreferrer">View my LinkedIn Profile</a> 

theme: jekyll-theme-minimal
#google_analytics: UA-000000-0 # your Google Analytics tracking ID here

---
useMath: true
---
